spring:
  profiles:
    active: local   # 或 docker，启动时可以覆盖



#spring:
#  application:
#    name: gateway-service
#
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848    # 改成你的 nacos 地址
#      config:
#        file-extension: yaml        # dataId 必须以 .yaml 结尾
#        group: DEFAULT_GROUP
#        namespace: public           # 默认是 public，可以省略
#
## 重点：引入 nacos 配置
#spring.config.import: nacos:${spring.application.name}.yaml
#
#
#
