server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      # =======================
      # 全局 CORS 配置
      # =======================
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"   # 支持任意来源
            allowedMethods: "*"          # GET, POST, PUT, DELETE 等
            allowedHeaders: "*"          # 所有请求头
            allowCredentials: true       # 支持 cookie 或 Authorization
            maxAge: 3600                 # 缓存预检请求时间，单位秒

      # =======================
      # 服务发现 + 路由
      # =======================
      discovery:
        locator:
          enabled: true               # 使用服务名路由
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: acg-product-service
          uri: lb://acg-product-service
          predicates:
            - Path=/api/courses/**

        - id: acg-rating-service
          uri: lb://acg-rating-service
          predicates:
            - Path=/api/enrollments/**

# =======================
# JWT 配置
# =======================
jwt:
  secret: "MySuperSecureJwtSecretKeyForHS256_123456"
  expiration: 86400000  # 24h
