##server:
##  port: 8081
##
##spring:
##  application:
##    name: user-service
##
##  datasource:
##    url: jdbc:mysql://localhost:3306/acg_user_db?useSSL=false&serverTimezone=Asia/Shanghai
##    username: root
##    password: "00000712"
##
##  jpa:
##    hibernate:
##      ddl-auto: update
##    show-sql: true
##
##  cloud:
##    nacos:
##      discovery:
##        server-addr: localhost:8848     # 本地访问 Nacos
##        heart-beat-interval: 5000       # 5 秒发心跳
##        heart-beat-timeout: 20000       # 20 秒无响应视为挂了
##        health-check-url: /actuator/health
##        ephemeral: true
##
##management:
##  endpoints:
##    web:
##      exposure:
##        include: health,info
##
##feign:
##  circuitbreaker:
##    enabled: true  # 开启 Feign 熔断
##
##resilience4j:
##  circuitbreaker:
##    instances:
##      catalogService:
##        registerHealthIndicator: true
##        slidingWindowSize: 10
##        minimumNumberOfCalls: 5
##        failureRateThreshold: 50
##        waitDurationInOpenState: 5s
##
##jwt:
##  secret: "MySuperSecureJwtSecretKeyForHS256_123456"
##  expiration: 86400000  # 24h
#
##spring:
##  profiles:
##    active: local   # 或 docker，启动时可以覆盖
##
#
#spring:
#  application:
#    name: user-service
#
#  config:
#    # 导入 Nacos 配置（可选）
#    import: "optional:nacos:"
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
#        heart-beat-interval: 5000
#        heart-beat-timeout: 20000
#        health-check-url: /actuator/health
#        ephemeral: true
#      config:
#        enabled: true
#        # 禁用 import 检查（可选，避免启动报错）
#        import-check: false
#
#server:
#  port: 8080
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#spring:
#  profiles:
#    active: local

spring:
  application:
    name: user-service

  cloud:
    nacos:
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: public

spring.config.import: nacos:${spring.application.name}.yaml


