#server:
#  port: 8081
#
#spring:
#  application:
#    name: user-service
#
#  datasource:
#    url: jdbc:mysql://acg-demo-mysql:3306/acg_user_db?useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 00000712
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        show_sql: true
#      jakarta:
#        persistence:
#          jdbc:
#            url: jdbc:mysql://acg-demo-mysql:3306/acg_user_db?useSSL=false&serverTimezone=Asia/Shanghai
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: nacos:8848
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://acg-demo-mysql:3306/acg_user_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "00000712"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        health-check-url: /actuator/health
        ephemeral: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      catalogService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

jwt:
  secret: "MySuperSecureJwtSecretKeyForHS256_123456"
  expiration: 86400000






#server:
#  port: 8081
#
#spring:
#  application:
#    name: user-service
#
#  datasource:
#    url: jdbc:mysql://acg-demo-mysql:3306/acg_user_db?useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: "00000712"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
#jwt:
#  secret: "MySuperSecureJwtSecretKeyForHS256_123456"
#  expiration: 86400000


#spring:
#  cloud:
#    nacos:
#      server-addr: nacos:8848
